# 
# policy_path: "{LEGGED_GYM_ROOT_DIR}/deploy/pre_train/bhr8/policy_lstm_1.pt"
policy_path: "{LEGGED_GYM_ROOT_DIR}/logs/bhr8/exported/policies/policy_lstm_1.pt"
# policy_path: "{LEGGED_GYM_ROOT_DIR}/deploy/pre_train/g1/g1_21dof_policy_lstm_1.pt"
# policy_path: "{LEGGED_GYM_ROOT_DIR}/deploy/pre_train/g1/motion.pt"
xml_path: "{LEGGED_GYM_ROOT_DIR}/resources/robots/bhr8fc2/scene.xml"
show_log_plot: True

# Total simulation time
simulation_duration: 20
# Simulation time step
simulation_dt: 0.002
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 10

# g1 12dof
kps: [250, 250, 300, 300, 80, 80, 
      250, 250, 300, 300, 80, 80]
kds: [2, 2, 3, 3, 2, 2, 
      2, 2, 3, 3, 2, 2]

default_angles: [0., -0.0, -0.3, 0.6, -0.3, 0.0, 
                  0., 0.0, -0.3, 0.6, -0.3, -0.0]

ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
cmd_scale: [2.0, 2.0, 0.25]

# g1 12dof
num_actions: 12
num_obs: 47
cmd_init: [0.2, 0.0, 0]
