# 
# policy_path: "{LEGGED_GYM_ROOT_DIR}/deploy/pre_train/g1/motion.pt"
policy_path: "{LEGGED_GYM_ROOT_DIR}/logs/g1_14dof/exported/policies/policy_lstm_1.pt"
# policy_path: "/home/robot/workspace/unitree_rl_gym/deploy/pre_train/g1/g1_21dof_policy_lstm_1.pt"
xml_path: "{LEGGED_GYM_ROOT_DIR}/resources/robots/g1_description/scene.xml"
show_log_plot: True
show_plot_time: 8
# Total simulation time
simulation_duration: 15.0
# Simulation time step
simulation_dt: 0.001
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 4

# # g1 12dof
# kps: [100, 100, 100, 150, 40, 40, 100, 100, 100, 150, 40, 40]
# kds: [2, 2, 2, 4, 2, 2, 2, 2, 2, 4, 2, 2]

# default_angles: [-0.1,  0.0,  0.0,  0.3, -0.2, 0.0, 
#                   -0.1,  0.0,  0.0,  0.3, -0.2, 0.0]

# g1 21dof
kps: [100, 100, 100, 150, 40, 40, 
      100, 100, 100, 150, 40, 40,
      80, 80] 
      # 100, 100, 100, 40, 40, 
      # 100, 100, 100, 40, 40] 
kds: [2, 2, 2, 4, 2, 2, 
      2, 2, 2, 4, 2, 2, 
      2, 2]
      # 2, 2, 2, 2, 2,
      # 2, 2, 2, 2, 2] 

default_angles: [-0.1,  0.0,  0.0,  0.3, -0.2, 0.0, 
                 -0.1,  0.0,  0.0,  0.3, -0.2, 0.0,
                  0.0, 0.0]
                  # 0.0, 0.0, 0.0, 0.0, 0.0, 
                  # 0.0, 0.0, 0.0, 0.0, 0.0]

ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
cmd_scale: [2.0, 2.0, 0.25]

# # g1 12dof
# num_actions: 12
# num_obs: 47

# g1 21dof
num_actions: 14
num_obs: 53
cmd_init: [0.0, 0, 0]
